version: '3.8'

services:
  db:
    image: mysql:8
    container_name: 'db'
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3307:3306'
  app:
    build: ./
    depends_on:
      - db
    container_name: 'java-app'
    ports:
      - '8080:8080'
    environment:
      - spring.datasource.url=jdbc:mysql://db:3306/db?serverTimezone=UTC
      - spring.datasource.username=root
      - spring.datasource.password=password
      - spring.flyway.enabled=true
      - spring.flyway.url=jdbc:mysql://db:3306/db?serverTimezone=UTC
      - spring.flyway.user=root
      - spring.flyway.password=password
      - spring.flyway.group=true
