version: '3.8'

services:
  db:
    image: mysql:8
    container_name: 'backofficeServiceDb'
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3307:3306'
    networks:
      - my-network
  app:
    build: ./
    depends_on:
      - db
    container_name: 'backofficeServiceApp'
    ports:
      - '8082:8080'
    networks:
      - my-network
    environment:
      - spring.datasource.url=jdbc:mysql://backofficeServiceDb:3306/db?serverTimezone=UTC
      - spring.datasource.username=root
      - spring.datasource.password=password
      - spring.flyway.enabled=true
      - spring.flyway.url=jdbc:mysql://backofficeServiceDb:3306/db?serverTimezone=UTC
      - spring.flyway.user=root
      - spring.flyway.password=password
      - spring.flyway.group=true
      - spring.kafka.bootstrap-servers=kafka:9092
      - user.service.app.name=user-service
      - spring.application.name=backoffice-service
      - eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
networks:
  my-network:
    external:
      name: car-sharing